from django.test import TestCase, Client
import capstoneMain.ToolOwnershipTracker.models

class checkTitleTests(TestCase):
    def setup(self):
        tempTitle="test"

    def testPositiveWithTitle(self):
        assertIsTrue(checkTitle(self,tempTitle))

    def testNegativeWithoutTitle(self):
        assertIsFalse(checkTitle(self,tempTitle))
        self.assertRaises(Exception):
            checkTitle(self, "")

class assignOwnerTests(TestCase):
    def setup(self):
        tempUser = User(firstName = "test", lastName = "test", email = "test", password = "test", address = "test", phone = "test")
        tempUser.save()

    def testPositiveWithUser(self):
        assertIsTrue(assignOwner(self,tempUser))

    def testNegativeWithNoUser(self):
        assertIsFalse(assignOwner(self, "fakeuser")
        self.assertRaises(Exception):
            assignOwner(self, "fakeuser")

class addUserTest(TestCase):
     def setup(self):
        tempUser = User(firstName = "test", lastName = "test", email = "test", password = "test", address = "test", phone = "test")
        tempUser.save()

     def testPositiveWithUser(self):
        assertIsTrue(addUser(self,tempUser))

     def testNegativeWithoutUser(self):
        assertIsFalse(addUser(self,"fakeuser"))
        self.assertRaises(Exception):
            addUser(self,"fakeuser")

     #TODO Jobsite does not currently check if the user already exists may cause duplicates


